# 예외처리
## 에러(Error)
> 어떤 원인에 의해 오동작하거나 비정상적으로 종료되는 경우
### 발생 시점에 따른 구분
- 컴파일 에러(compile-time error)
    - 컴파일 도중 컴파일러가 발견하는 오류
- 런타임 에러(runtime error)
    - 컴파일은 성공적으로 진행되었으나, 프로그램 실행 중에 발생하는 오류
- 논리적 에러(logical error)
    - 컴파일도 되고 프로그램도 실행되었으나, 프로그램이 의도대로 동작하지 않는 오류. 
    - 프로그램이 정상적으로 실행되고 종료되었지만 결과가 예상과 다른 경우
### 에러와 예외
- 에러: 발생하면 복구할 수 없는 심각한 오류
    - (예: 메모리 부족, 스택 오버 플로우 등)
- 예외: 프로그래머가 적절한 코드를 통해 대비할 수 있는 오류
    (예: 클래스 형 변환 실패, 파일 읽기 실패 등)

## 예외처리
- 예외 발생 시 프로그램의 비정상 종료를 막고 정상적인 실행 상태를 유지하는 것
- 예외의 감지 및 예외 발생 시 동작할 코드 작성 필요

### 예외의 종류
- 체크 예외(Checked Exception)
    - 컴파일 시점에서 예외 처리가 요구되는 예외
    - IDE에서 코드 작성 시 빨간 밑줄
    - (예: IOException, SQLException)
- 언체크 예외(Unchecked Exception)
    - 실행 시점에서 발생하는 예외로, 컴파일러가 예외 처리를 강제하지 않음
    - 컴파일 자체는 완료되며, 파일 실행가능
    - (예: NullPointerException, ArrayIndexOutOfBoundsException)

### 예외처리 키워드
- 직접 처리
    - `try {}`: 예외가 발생할 가능성이 있는 코드를 포함하는 블록
    - `catch (예외매개변수) {}`: 예외가 발생했을 때 실행할 코드 블록
    - `finally {}`: 예외 발생 여부와 상관없이 항상 실행되는 코드 블록
- 간접 처리
    - `throws`: 메서드 시그니처에 사용되며, 해당 메서드가 특정 예외를 던질 수 있음을 명시
- 예외를 직접 발생시킬 때
    - `throw`: 예외를 명시적으로 발생시키는 키워드

## try ~ catch 구문
- 프로그램 실행 시 발생할 수 있는 예외에 대한 대비코드 작성
- 프로그램의 비정상적인 종료를 막고, 정상적인 상태를 유지할 수 있도록 함.
```java
try {
    // (1) 정상코드
    // (2) 예외가 발생할 수 있는 코드
    // (3) 정상코드
}
catch (SomeException e) {
    // (4) 예외가 발생했을 때 처리할 코드
}
// (5) 일반코드
```
- 실행 순서
    - 예외가 발생하지 않았을 때 : 1 - 2 - 3 - 5
    - 예외가 발생했을 때
        - catch 되었을 때 : 1 - (2) - 4 - 5
        - catch(예외처리) 실패했을 때 : 1 - (2 - 비정상적 종료)
- 중괄호(블록) 생략 불가능
- 중첩된 예외처리: 블록 안에 또 다른 try ~ catch 구문이 올 수 있음

### 다중 예외처리
- try 블록에서 여러 종류의 예외가 발생할 경우 하나의 try 블록에 여러 개의 catch 블록 추가 가능
- 예외 객체에 해당하는 catch 문장을 찾을 때는 다형성이 적용됨
- 상속 관계에서 상위 타입의 예외가 먼저 선언되는 경우 뒤에 등장하는 catch 블록은 동작할 기회가 없음
- 상속 관계가 없는 경우는 무관
- 상속 관계는 작은 범위(자손)에서 큰 범위(조상) 순으로 정의
```java
// 1.
try {
    // 예외가 발생할 수 있는 코드
} catch (XXException e) {
    // XXException 발생 시 처리 코드
} catch (YYException e) {
    // YYException 발생 시 처리 코드
}

// 2.
try {
    // 예외가 발생할 수 있는 코드
} catch (XXEXception | YYException e) {
    // 필요 시 instanceof를 통해 나누어 작성

    // XXException 발생 시 처리 코드
    // YYException 발생 시 처리 코드
}
```
### Exception 인스턴스의 주요 메서드
- `getMessage()`: 발생된 예외에 대한 구체적인 메시지를 반환
- `printStackTrace()`: 예외 발생 당시의 호출 스택(Call Stack)을 출력한다.
- catch 구문에 사용 가능

## throws
- 메서드가 예외를 처리하는 것이 아니라 나를 호출한 곳으로 전달하는 것
    - 메서드 내에서 예외처리 하지 않았으니, 메서드 호출 시 직접 예외처리 하라는 의미 
- 메서드 선언부에 `throws` 키워드를 사용하여 예외 작성
- 예외가 여러 개일 경우 `,`를 이용하여 나열
- 조상 타입의 예외로 처리 가능(다형성)

### throws의 의미
- 메서드를 정의하는 프로그래머
    - 메서드에서 예외 처리하지 않고 이 메서드를 사용하는 사람이 예외를 처리해서 쓰도록
- 메서드를 사용하는 프로그래머 
    - 이 메서드는 ... 예외(CheckedException)를 발생시킬 수 있음 → 사용하기 위해선 예외 처리해야 함
- 컴파일러 
    - 원래 예외 처리가 강제되나, 메서드 선언하며 throws 키워드 작성 시 메서드 본문 내에서만 통과. 
    - 메서드 호출부에서는 예외 처리 강제

### Checked Exception과 throws
```java
public static void main(String[] args) {
    // 예외 전달받은 main 메서드에서는 예외 처리 필요
    try {
        method1();
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    }
}

public static void method1() throws ClassNotFoundException {
    method2();  // 메서드 호출부 : throws로 예외 전달됨
                // method1에서도 throws를 통해 메인 메서드로 예외 전달
}

public static void method2() throws ClassNotFoundException {
    Class.forName("Hello"); // CheckedException 발생
} 
```

### Unchecked Exception과 throws
- 컴파일러가 예외 처리를 강제하지 않음
- 따라서 UncheckedException에게 throws는 아무런 의미가 없다.
```java
public static void main(String[] args) {
    // - UncheckedException : 컴파일러가 예외처리를 강제하지 않음
    // - throws : 이번 한번만 봐줄게
    // - 예외가 실행중에 발생하면 프로그래머의 자율에 맡김.
    try {
        method1();
    } catch ()
}

public void method1() {
    method2();
}

public void method2() {
    int i = 1 / 0;
} 
```
### 메서드 재정의와 throws
- 메서드 재정의 시 조상클래스 메서드가 던지는 예외보다 부모 예외를 던질 수 없다.

```java
class Parent {
    void methodA() throws IOException { }
    void methodB() throws ClassNotFoundException { }
}

public class Child extends Parent {
    @Override
    void methodA() throws FileNotFoundException { }

    @Override
    void methodB() throws Exception { } // Exception은 모든 예외의 조상 클래스
                                        // Parent에는 하위 클래스의 예외에 대한 대비만 되어있을 것
                                        // Child에서 재정의 한 예외에 대한 처리 불가
}
```

## finally 구문
- finally는 예외 발생 여부와 상관 없이 언제나 실행
```java
try {
    // 예외가 발생할 수 있는 코드
} catch(SomeException e) {
    // 예외 처리 코드
} finally {
    // 예외 상관 없이 항상 수행해야 하는 코드
}
```
- 예외 발생 시 : try - catch - finally
- 예외 미발생 시 : try - finally
- 중간에 return 있어도 finally 블록 수행 후 반환함

## 자동 자원 반납 구문 (try with resources)
- 자원 등을 반납할 때 finally에서 `close()`를 통해 주로 반납함.
- 코드가 지저분해지고 다른 예외 상황을 발생시킬 수 있음
```java
FileInputStream fis = null;     // 파일 입력 받기
try {
    fis = new FileInputStream("test.txt");
} catch (IOException e) {
    e.printStackTrace();
} finally {
    try {
        if (fis != null) {
            fis.close();        // 자원 반납(입력 그만 받기)
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

- `try ()` → 괄호 안에 객체를 생성하는 코드를 작성하면, 해당 객체는 `close()`를 호출하지 않아도 블록을 벗어나는 순간 `close()`가 호출됨
- 해당 객체의 클래스가 `AutoCloseable`이라는 인터페이스를 구현한 클래스여야만 함.
```java
try (FileInputStream fis = new FileInputStream("test.txt")) {
    // 
} catch (IOException e) {
    e.printStackTrace();
}
```
## 사용자 정의 예외
- 기존에 정의된 예외 이외에 사용자가 직접 정의 예외를 작성할 수 있음
- 대부분 Exception 또는 RuntimeException 클래스를 상속받아 작성
    - checked exception 활용:
        - 명시적 예외처리 또는 throws 필요
        - 코드는 복잡해지지만 처리, 누락 등 오류 발생 가능성 ↓
        ```java
        public class FruitNotFoundException extends Exception {
            public FruitNotFoundException(String name) {
                super(name + "에 해당되는 과일이 없습니다.");
                // 생성자에 넣는 문자열 : 예외 메시지
            }
        }

        public static void main(String[] args) {
            try {
                method1();
            } catch (FruitNotFoundException e) {
                e.printStackTrace();
            } 
        }

        private static void method1() throws FruitNotFoundException {
            // 예외 직접 발생시킬 때는 throw 키워드 사용
            throw new FruitNotFoundException("사과")
        }
        ```
    - runtime exception 활용 
        - 묵시적 예외처리 가능
        - 코드 간결해지지만 예외 처리, 누락 가능성 발생
        ```java
        public class FruitNotFoundRuntimeException extends Exception {
            public FruitNotFoundRuntimeException(String name) {
                super(name + "에 해당되는 과일이 없습니다.");
                // 생성자에 넣는 문자열 : 예외 메시지
            }
        }

        public static void main(String[] args) {
            method2();
        }

        private static void method2() {
            // 예외 직접 발생시킬 때는 throw 키워드 사용
            throw new FruitNotFoundRuntimeException("귤")
        }
        ```